### PR TITLE
Darker dark-mode

### PR DESCRIPTION
**Pull request by elias123tre**
A darker dark-mode, with colors from a color palette ([tailwindcss](https://tailwindcss.com/docs/customizing-colors) slate-700, slate-800). And some different white shades (Anti-Flash White, Chinese White).

Additionally a lighter glow instead of a normal shadow when dark-mode is applied to prevent a dark shadown on dark backgound.

These are of course stylistic changes so feel free to reject the PR if it doesn't fit the style :)

### CODE REVIEW

**Comment by elias123tre** [comment]
A side by side comparison of the current (left) and my proposal (right) styles for dark-mode.
side by side (old left, new right)

**Comment by Neikon** [comment]
I like it, @andreasgrafen what do you think?

**Comment by andreasgrafen** [comment]
> I like it, @andreasgrafen what do you think?

Not the biggest fan of the background colour and shadow tbh. I personally thing lighter shadows look odd. o:
**But** if the majority likes this better it's ofc completely fine to merge this. I use the light mode anyway. xd

**Comment by BeyondMagic** [comment]
I guess it's more vivid, not really 'darker', I like it anyway.

**Comment by BeyondMagic** [comment]
Should we merge it?

**Comment by Neikon** [comment]
> Should we merge it?

yes, it's fine for me

**Comment by BeyondMagic** [comment]
All right.

**Pull request merged**
