### PR TITLE
add disclaimer

### PR DESCRIPTION
**Pull request by Neikon**
just in case it's better to have something like this. Have a look at it in case something needs to be changed. Both in the way of including it in the web and in the text itself.

### CODE REVIEW

**Comment by andreasgrafen** [comment]
A disclaimer doesn't harm anyone. Neat idea. ^—^

I've converted the disclaimer over to Pug. During this process I've split up the pug files into templates and includes for easier handling. To make sure that everything looks nice I've added some stuff to `typography.scss` and fixed some issues that came along with this.

**Review by andreasgrafen — APPROVED** [review]

**Comment by BeyondMagic** [comment]
Any particular reason to have a disclaimer?

**Comment by andreasgrafen** [comment]
> Any particular reason to have a disclaimer?
Just as a general safety measure, I think. Especially since we're linking almost exclusively to third party content.

**Comment by Neikon** [comment]
if for any reason any of the themes we link to causes a problem for any user. Users should be aware that we do not assume any responsibility. This kind of themes can be very powerful and also dangerous as they can do whatever they want with the browser. Those possible risks is the main reason why they are "forced" to provide themselves via github and just the way they do it. No automatic installers or anything that could hide a malicious purpose.

So if one day something happens we wash our hands and we will not have any responsibility or problem.

**Comment by BeyondMagic** [comment]
I mean, I got you, but this is a github project that links to others github projects. The site iself is not selling anything to anyone, *even with its name*, like, "use this theme to resolve all your problems" - lol - the themes themselves have their own ways to install, and those have their own creators; the responsibility of ours is only to share themes, we don't need a disclaimer... but... like andreasgrafen said, it won't hurt.

**Comment by Neikon** [comment]
> 
> 
> I mean, I got you, but this is a github project that links to others github projects. The site iself is not selling anything to anyone, _even with its name_, like, "use this theme to resolve all your problems" - lol - the themes themselves have their own ways to install, and those have their own creators; the responsibility of ours is only to share themes, we don't need a disclaimer... but... like andreasgrafen said, it won't hurt.

Of course, it's common sense, but just in case, it's better to have it.

**Comment by BeyondMagic** [comment]
Hmmmm.

**Pull request merged**
