### PR TITLE
Little fix and new pictures

### PR DESCRIPTION
**Pull request by Neikon**
I add a 5px margin to social icons in the footer, Check if i did it right, pls

And I upload our own picture in webp to make faster the web

### CODE REVIEW

**Review by andreasgrafen — APPROVED** [review]
Looking good! The rewrite to PUG apparently got rid of the native spacing between the footer elements. The CSS makes for a good fix. WEBP pictures are always awesome.

**Review by BeyondMagic — APPROVED** [review]
We'll need to make a way to automatize this process to optimize images (transforming them into WEBP).

**Review by BeyondMagic — CHANGES_REQUESTED** [review]
Actually, build the project to make the changes in the dest, or add it to the CSS main file.

**Comment by Neikon** [comment]
> 
> 
> Actually, build the project to make the changes in the dest, or add it to the CSS main file.

I'm sorry but I didn't understand what I have to change in order to make the merge.

in other hand we already have a bot to optimise the images, let's see if I can find one that also converts them to webp.

**Comment by andreasgrafen** [comment]
> I'm sorry but I didn't understand what I have to change in order to make the merge.

If I understood this correctly you're asked to run a build real quick to make the changes in the sass compile into the css file. Right now the extra margin forr the social icons wouldn't take effect. If you have the node modules installed you can just run `npm run build` or `gulp` – or use whateve way you're comfortable with. c:

Worst case is to merge it like it is now and just run the build on the main branch.

Regarding the images bot I don't have any doubt that we can find something that suits our needs. ^—^

**Comment by BeyondMagic** [comment]
The project is using **NPM** + **gulp** to build the **dev** folder, it passes clean and minimized files to our root and **assets**. You can install it by running `npm install` in the project and then build it with the script in package.json, `npm run build`.

The line that you added on the _footer.scss would be parsed all together to the .css main file, adding the same line there, too. I can build it if you want, too, so I'm waiting the merge.

**Comment by Neikon** [comment]
I've tried but I don't know what I'm doing wrong.
i've installed this to run npm in visual studio code (i don't know if this is enough), 
and i do "Ctrl+P, write `>npm`, select `run build` , `run scripr` `run start` or whatever " and any work :'( 
imagen

**Comment by BeyondMagic** [comment]
There's no problem, I'll merge and build. I don't even remember what was the last time I used VSCode, so I can't help you a lot with it, but it seems that `npm` is not in your path, maybe VSCode didn't have enough permissions to put it there or you just need to do it manually; sorry, again, I don't know how to do that in Windows, but, like I said, it's just a minor issue for now.

**Review by BeyondMagic — APPROVED** [review]
^

**Pull request merged**
