### PR TITLE
Frontend Rewrite

### PR DESCRIPTION
**Pull request by unseen-ninja**
Cheers! o/

I've wanted to do this for a while since there are a few things that bug me about the current state of the frontend – I was young and naive back when I did those things. :^)

With this PR I'm proposing a rewrite of the frontend using [Astro](https://astro.build/) in order to generate fully static files in order to reduce all the clientside efforts currently in place.

**As of right now this breaks two things**:
- **Search:** Which so far is intended as I feel like the search is lacking anyway – which is more due to lazy tagging by theme authors than anything else. I have instead opted for visible tags on each theme's card.
- **Theming** (partially): The CSS is set up to follow the users preferred (browser-set) colour scheme to avoid placing things in local storage in order to avoid GDPR issues.

Besides that I've improved a couple visual things and I intentionally split the most recent themes from the rest and placed two cards inbetween to guide users to other resources.

A live preview of everything is available on [GitHub Pages](https://andreasgrafen.github.io/ffcss-website/).

ffcss-dark

ffcss-light

### CODE REVIEW

**Comment by BeyondMagic** [comment]
Pretty darn beautiful!

**Comment by Zabooby** [comment]
Wow this looks amazing!

**Comment by Neikon** [comment]
Looks awesome, good job.

I tried the live preview you made and went straight into the dark version without doing anything (I have everything on dark) so I think that part works, at least for me.

**Comment by andreasgrafen** [comment]
I'm glad this is well received. c:

There still are a couple quirks to iron out, as well as all the build and test process stuff – not sure if and what has to be changed for that to work. And once that's done I'll have to rethink the search. I surely am _not_ looking forward to that, but I guess it's a feature that we wanna keep?


> I tried the live preview you made and went straight into the dark version without doing anything (I have everything on dark) so I think that part works, at least for me.

This has been supported in browsers for a while, so I guess it shouldn't really conflict with anything. And in case it's not supported or the user doesn't allow access to that information it will just default to light – tho that could also just be switched around in case we would prefer that.

**Comment by Neikon** [comment]
> I'm glad this is well received. c:
> 
> There still are a couple quirks to iron out, as well as all the build and test process stuff – not sure if and what has to be changed for that to work. And once that's done I'll have to rethink the search. I surely am _not_ looking forward to that, but I guess it's a feature that we wanna keep?
> 

If possible, I would like to have a search engine. Because we already have 100 topics and several to come. It can be a bit complex to find something among so many candidates. 
Although... it occurs to me right now as I write that at a bad time. You could make the tags visible under the topics and tell the user to use ctrl+F to search.

**Comment by Zabooby** [comment]
> I'm glad this is well received. c:
> 
> There still are a couple quirks to iron out, as well as all the build and test process stuff – not sure if and what has to be changed for that to work. And once that's done I'll have to rethink the search. I surely am _not_ looking forward to that, but I guess it's a feature that we wanna keep?
> 
> > I tried the live preview you made and went straight into the dark version without doing anything (I have everything on dark) so I think that part works, at least for me.
> 
> This has been supported in browsers for a while, so I guess it shouldn't really conflict with anything. And in case it's not supported or the user doesn't allow access to that information it will just default to light – tho that could also just be switched around in case we would prefer that.

With so many themes now on the store I think it would be great to be able to filter by updates, so users can find working themes much quicker.

**Comment by Neikon** [comment]
> With so many themes now on the store I think it would be great to be able to filter by "recently updated", so users can find working themes much quicker.

That's not possible, I would need to monitor each and every theme or tell the authors to send status updates to our repo and neither option is really feasible in the long run

**Comment by Zabooby** [comment]
> > With so many themes now on the store I think it would be great to be able to filter by "recently updated", so users can find working themes much quicker.
> 
> That's not possible, I would need to monitor each and every theme or tell the authors to send status updates to our repo and neither option is really feasible in the long run.
> 
> In fact, although we should do some review from time to time to see if a theme has been abandoned. Ideally, when a user detects it, he should send us an issue to delete the theme.

Maybe do a review at the end of each month or two?

**Comment by Neikon** [comment]
> Maybe do a review at the end of each month or two?

If someone wants to do it, I won't be the one to stop them XD.

15 mints per theme for 100 themes = 25 hours of work reviewing themes.

P.D: Sorry, I don't know how I ended up editing your post instead of writing a reply.

**Comment by Zabooby** [comment]
Would it really take 15 minutes per theme? 

Couldn't you just check when the repo was last updated, maybe have a cutoff point of ~1 year?

**Comment by BeyondMagic** [comment]
> Couldn't you just check when the repo was last updated, maybe have a cutoff point of ~1 year?

We could make a script to organise it automatically, and I have no problem making and taking care of it myself.

I think these ideas would be better suited for an issue rather than polluting this PR, care to create one?

**Comment by andreasgrafen** [comment]
I think the most important thing that happened over the latest commits is that I've put the asset handling entirely in Astro's hands. This means that we don't have to explicitly have the `.wepb` filetype in `themes.json` as Astro will handle all that. (meaning we no longer need to run `img-switch.sh`.) All CI steps are updated accordingly.

This changes the notation inside the `themes.json` which is now located in the `src` directory. All images are now stored in `src/assets`.
```json
[…]
  "image": "/src/assets/*.{webp,jpeg,jpg,png,gif}",
[…]
```


@Neikon 
> You could make the tags visible under the topics and tell the user to use ctrl+F to search.

I've highlighted the tags a little more using a similar style as GitHub with the pills. I'll still look into the search, but it's probably not as easy as it was previously since everything is static now. :/

**Comment by Zabooby** [comment]
Is the red colour scheme final? I love the blue on the current site, it would fit with the logo too.

**Comment by andreasgrafen** [comment]
The colour scheme is more or less fixed in the sense that I'm using [Rosé Pine](https://github.com/rose-pine). But that doesn't mean that we can't change the colour we use for links, or even introduce a completely new one. I just picked `love` because the contrast fits well. c:

**Comment by BeyondMagic** [comment]
Oh, unbeknownst to me, but did you want to close it, @unseen-ninja?

**Comment by unseen-ninja** [comment]
Oh, shit. I've done some cleanup, and I forgot to whiteolist my original repo and it got deleted. This is entirely by accident. I do have a local copy tho. I'll re-open another PR, I guess. D:

**Pull request closed without merging**
