### PR TITLE
add starry-fox theme

### PR DESCRIPTION
**Pull request by sagars007**

### CODE REVIEW

**Comment by BeyondMagic** [comment]
Add tags about your theme.

**Comment by BeyondMagic** [comment]
Thank you for your addition.

**Comment by sagars007** [comment]
I think the readme should be updated to include that tags cannot be left empty in themes.json when opening a pull request.
Currently it only states: 
iv. [Add the properties of your theme: title, link, description and image](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io#add-your-theme-3)

**Comment by Neikon** [comment]
> I think the readme should be updated to include that tags cannot be left empty in themes.json when opening a pull request. Currently it only states: iv. [Add the properties of your theme: title, link, description and image](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io#add-your-theme-3)

Ready

**Comment by sagars007** [comment]
>  Ready

Awesome!👍

**Pull request merged**
